[env]
PHOTOJOURNALISM_SERVER = "0.0.0.0:9000"
PHOTOJOURNALISM_PAGE_SIZE = "6"
PHOTOJOURNALISM_FETCH_INTERVAL = "3600"
PHOTOJOURNALISM_STATIC_PATH = "$(pwd)"
PHOTOJOURNALISM_FEED_LIST = "$(pwd)/feeds.txt"